[phases.setup]
aptPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd server && npm ci",
  "cd ../client && npm ci"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cd ../server"
]

[phases.start]
cmd = "cd server && node server.js"

[start]
cmd = "node server/server.js"