[phases.setup]
# Install dependencies for both backend and frontend
run = "cd server && npm install && cd ../client && npm install"

[phases.build]
# Build the React frontend
run = "cd client && npm run build"

[phases.start]
# Start the backend server (ensure server.js is configured correctly)
run = "cd server && node server.js"
