[phases.setup]
aptPkgs = ["nodejs", "npm", "python3", "build-essential"]

[phases.install]
cmds = [
  "cd server && npm install",
  "cd ../client && npm install"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && node server.js"