[phases.setup]
aptPkgs = ["nodejs", "npm", "python3", "make", "g++"]

[phases.install]
cmds = [
  "npm ci --prefix server",
  "npm ci --prefix client"
]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "node server/server.js"
startCommand = "node server/server.js"